### ISSUE TITLE
docker: Error response from daemon (coyotebadger container not running)

### ISSUE THREAD

**Issue by TLR-RE** [alexsands/coyote-badger#8]
I am having an issue running the coyotebadger container on Docker (on my Intel processor Mac with Monterey OS V12.1). After running coyotebadger and seeing Build 28/28 appear successful, I get this message:

docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 

When I run 'docker ps' I get:

CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                NAMES
3814db9c1723   docker/getting-started   "/docker-entrypoint.…"   48 minutes ago   Up 29 minutes   0.0.0.0:80->80/tcp   infallible_neumann

And when I run 'docker ps -a' for stopped containers it shows up as:

CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                NAMES
b5b5d2fce2e3   coyotebadger:latest      "/bin/sh -c ./docker…"   20 minutes ago   Created                              coyotebadger
3814db9c1723   docker/getting-started   "/docker-entrypoint.…"   48 minutes ago   Up 29 minutes   0.0.0.0:80->80/tcp   infallible_neumann

I have tried resetting Docker to factory settings, deleting and reinstalling coyote badger, restarting the computer, removing coyotebadger container and trying again...nothing seems to be working. Found same issue in StackOverflow but didn't understand the fix: https://stackoverflow.com/questions/60289248/macos-rejects-all-the-available-ports-when-starting-a-docker

Is anyone else getting this Docker error? I am going to try running on another Mac tonight because it could just be something with my computer. Thanks!

**Comment by alexsands** [comment]
This cause of this issue was that Apple's Monterey update turned on AirPlay receiver by default, which uses port 5000. Coyote Badger also uses port 5000, so it failed to start. You can check if AirPlay is using port 5000 by entering the following in Terminal (and then typing your password):
```sh
sudo lsof -i :5000
```
If `ControlCe` shows up, you have AirPlay receiver turned on. You can disable it by following [these instructions](https://developer.apple.com/forums/thread/682332?answerId=678289022#678289022). Then re-run CB and it should work fine.

I'll also update CB to use port 5001 instead so that people won't run into this issue as frequently.

**Comment by TLR-RE** [comment]
Thank you!!
